name: Make New Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make release
      run: make build
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Commit latest
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: main
        FOLDER: /
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
    
