name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make new build
      run: make build
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy release
    - uses: s0/git-publish-subdir-action@develop
      needs: build
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}